function(pesto_compile_texture)
    set(options "")
    set(oneValueArgs ROOT TEXTURE ARRAY_NAME OUTPUT_FILE)
    set(multiValueArgs "")
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    bgfx_compile_binary_to_header(
            INPUT_FILE ${ARG_ROOT}/${ARG_TEXTURE}
            OUTPUT_FILE ${ARG_ROOT}/${ARG_OUTPUT_FILE}
            ARRAY_NAME ${ARG_ARRAY_NAME}
    )

endfunction()

function(pesto_compile_shader_to_header)
    set(options "")
    set(oneValueArgs ROOT TYPE SHADER VARYING_DEF HEADER OUTPUT_DIR)
    set(multiValueArgs "")
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    bgfx_compile_shader_to_header(
            TYPE ${ARG_TYPE}
            SHADERS ${ARG_ROOT}/${ARG_SHADER}
            VARYING_DEF ${ARG_ROOT}/${ARG_VARYING_DEF}
            OUTPUT_DIR ${ARG_ROOT}/${ARG_OUTPUT_DIR}
            INCLUDE_DIRS ${BGFX_DIR}/src
            OUT_FILES_VAR SHADERS_OUTPUT
    )

    foreach (SHADER ${SHADERS_OUTPUT})
        get_filename_component(SHADER_FILE_NAME ${SHADER} NAME)
        list(APPEND COMMANDS COMMAND echo \#include \"${SHADER_FILE_NAME}\" >> ${ARG_ROOT}/${ARG_OUTPUT_DIR}/${ARG_HEADER})
    endforeach ()

    add_custom_command(
            OUTPUT ${ARG_ROOT}/${ARG_FRAGMENT}
            COMMAND ${CMAKE_COMMAND} -E echo "// Auto generated by Pesto" > ${ARG_ROOT}/${ARG_OUTPUT_DIR}/${ARG_HEADER} ${COMMANDS}
    )
endfunction()

function(pesto_compile_shaders_to_headers)
    set(options "")
    set(oneValueArgs ROOT VERTEX FRAGMENT VARYING_DEF HEADER OUTPUT_DIR)
    set(multiValueArgs "")
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    bgfx_compile_shader_to_header(
            TYPE VERTEX
            SHADERS ${ARG_ROOT}/${ARG_VERTEX}
            VARYING_DEF ${ARG_ROOT}/${ARG_VARYING_DEF}
            OUTPUT_DIR ${ARG_ROOT}/${ARG_OUTPUT_DIR}
            INCLUDE_DIRS ${BGFX_DIR}/src
            OUT_FILES_VAR SHADERS_OUTPUT
    )

    bgfx_compile_shader_to_header(
            TYPE FRAGMENT
            SHADERS ${ARG_ROOT}/${ARG_FRAGMENT}
            VARYING_DEF ${ARG_ROOT}/${ARG_VARYING_DEF}
            OUTPUT_DIR ${ARG_ROOT}/${ARG_OUTPUT_DIR}
            INCLUDE_DIRS ${BGFX_DIR}/src
            OUT_FILES_VAR FRAGMENT_OUTPUT
    )

    list(APPEND SHADERS_OUTPUT ${FRAGMENT_OUTPUT})

    foreach (SHADER ${SHADERS_OUTPUT})
        get_filename_component(SHADER_FILE_NAME ${SHADER} NAME)
        list(APPEND COMMANDS COMMAND echo \#include \"${SHADER_FILE_NAME}\" >> ${ARG_ROOT}/${ARG_OUTPUT_DIR}/${ARG_HEADER})
    endforeach ()

    add_custom_command(
            OUTPUT ${ARG_ROOT}/${ARG_FRAGMENT}
            COMMAND ${CMAKE_COMMAND} -E echo "// Auto generated by Pesto" > ${ARG_ROOT}/${ARG_OUTPUT_DIR}/${ARG_HEADER} ${COMMANDS}
    )

endfunction()